export const PRICE_MISMATCH_THRESHOLD_PERCENT = 2;

export type PriceStatus =
  | 'BUYBOX_MATCHED'
  | 'BUYBOX_MISMATCH_REVIEW'
  | 'AMAZON_BUYBOX_MISSING_USING_KEEPA'
  | 'KEEPA_BUYBOX_MISSING_USING_AMAZON'
  | 'NO_BUYBOX';
